"""init tables

Revision ID: 975b5e0ef425
Revises: 
Create Date: 2026-02-06 10:52:08.362676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '975b5e0ef425'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('road_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('stream_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial index is auto-created by GeoAlchemy2 for Geometry columns
    op.create_index(op.f('ix_cctvs_name'), 'cctvs', ['name'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cctv_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('anomaly_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_cctv_id'), 'detections', ['cctv_id'], unique=False)
    op.create_index(op.f('ix_detections_detected_at'), 'detections', ['detected_at'], unique=False)
    op.create_table('traffic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cctv_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('congestion_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_info_cctv_id'), 'traffic_info', ['cctv_id'], unique=False)
    op.create_index(op.f('ix_traffic_info_recorded_at'), 'traffic_info', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_info_recorded_at'), table_name='traffic_info')
    op.drop_index(op.f('ix_traffic_info_cctv_id'), table_name='traffic_info')
    op.drop_table('traffic_info')
    op.drop_index(op.f('ix_detections_detected_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_cctv_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_cctvs_name'), table_name='cctvs')
    op.drop_table('cctvs')
    # ### end Alembic commands ###
